export const homeObjOne = {
    lightBg: true,
    primary: true,
    imgStart: '',
    lightTopLine: true,
    lightText: false,
    lightTextDesc: false, 
    topLine: 'Promoción',
    headline: 'Feliz Navidad!',
    buttonLabel: 'Ver más promociones de navidad',
    description: 'Este mes tenemos especial en promociones de articulos y muebles. Para que salgas de lo tuyo y traigas algo nuevo... digo, usado.',
    featuredImg: require('../../assets/nintendo-switch.jpg').default,
    featuredTitle: 'Nintendo Switch',
    featuredDescription: 'Como nuevo, incluye caja y accesorios.',
    featuredLink: '/',
    start: '',
    topspacing: true,
    promoted: true,
    shortDesc: true,
};

export const homeObjTwo = {
    lightBg: false,
    primary: true,
    imgStart: 'start',
    lightTopLine: true,
    lightText: true,
    lightTextDesc: true, 
    topLine: 'Boletín',
    headline: 'Acceso a tu articulo directamente!',
    buttonLabel: 'Ir a la pagina de impresión',
    description: 'Utiliza nuestra herramienta para crear e imprimir un afiche para poner junto a tu articulo en venta.', 
    featuredImg: require('../../assets/afiche-printing.png').default,
    featuredTitle: '',
    featuredDescription: '',
    featuredLink: '/',
    topspacing: false,
    promoted: false,
};

export const homeObjThree = {
    lightBg: true,
    primary: true,
    imgStart: '',
    lightTopLine: true,
    lightText: false,
    lightTextDesc: false, 
    topLine: 'Puerto Rico Conectado',
    headline: 'Un producto puertoriqueño en la isla.',
    buttonLabel: 'Saber mas sobre el proyecto',
    description: 'El proyecto forma parte de un pacto para proveer las mejores herramientas digitales, accesibles y gratuitas; con el proposito de impulsar una economia de información en la isla.', 
    featuredImg: require('../../assets/pr-grid.svg').default,
    featuredTitle: '',
    featuredDescription: '',
    featuredLink: '/',
    topspacing: false,
    promoted: false,
};